version: "3.6"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--serversTransport.rootCAs=certs/local-cert.pem.crt,certs/local-key.pem"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`mbp-traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.api@internal.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.routers.traefik.entrypoints=https"
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Map the static conf into the container
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic conf into the container
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hasura
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - proxy

  hasura:
    container_name: "mbp-hasura"
    image: hasura/graphql-engine:latest
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://root:secret@postgres:5432/postgres"
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "myadminsecretkey"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`mbp-hasura.localhost`)"
      - "traefik.http.routers.hasura.entrypoints=https"
      - "traefik.http.routers.hasura.service=hasura"
      - "traefik.http.routers.hasura.tls=true"
      - "traefik.http.services.hasura.loadbalancer.server.port=8080"
    networks:
      - proxy

  web:
    container_name: "mbp-web"
    image: "mybodypro.fit/mbp-web"
    ports:
      - "3000:3000"
    environment:
      AUTH0_BASE_URL: "https://mbp-web.localhost"
      HASURA_GRAPHQL_URL: "mbp-hasura.localhost/v1/graphql"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`mbp-web.localhost`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    networks:
      - proxy
    volumes:
      - .:/src:delegated
      - /src/node_modules

networks:
  proxy:
    external: true

volumes:
  db_data: