version: "3.3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`mbp-traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    container_name: "mbp-web"
    env_file: .env
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      AUTH0_BASE_URL: mbp-web.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`mbp-web.localhost`)"
      - "traefik.http.routers.web.entrypoints=web"