http:
  routers:
    traefik:
      rule: "Host(`mbp-traefik.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "localhost"
            sans:
              - "*.localhost"
          - main: "mbp-traefik.localhost"
            sans:
              - "*.mbp-traefik.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"